name:  CICD for pipeline

on: 
  push:
    branches:           
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: use node js
        uses: action/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }} 
      - name: npm install and build
        run: |
          npm install
          npm run build

        env:
          CI: true
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              curl-o- https://raw.githubusercontext.com/creationix/nvm/v0.33.8/install.sh   |bash
              . ~/.nvm/nvm.sh

               nvm install 14
               npm install -g pm2
               cd ~/CICD
               git pull origin main
               npm install
               npm run build
               pm2 restart api

